//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceTutorias
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estudiante", Namespace="http://schemas.datacontract.org/2004/07/TutoriasWcf.App_Data")]
    public partial class Estudiante : object
    {
        
        private string apellidosField;
        
        private string carreraField;
        
        private string contrasenaField;
        
        private string correoField;
        
        private int idEstudianteField;
        
        private string matriculaField;
        
        private string nombreField;
        
        private string nombreTutorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidos
        {
            get
            {
                return this.apellidosField;
            }
            set
            {
                this.apellidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string carrera
        {
            get
            {
                return this.carreraField;
            }
            set
            {
                this.carreraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasena
        {
            get
            {
                return this.contrasenaField;
            }
            set
            {
                this.contrasenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                this.correoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idEstudiante
        {
            get
            {
                return this.idEstudianteField;
            }
            set
            {
                this.idEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matricula
        {
            get
            {
                return this.matriculaField;
            }
            set
            {
                this.matriculaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreTutor
        {
            get
            {
                return this.nombreTutorField;
            }
            set
            {
                this.nombreTutorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Turno", Namespace="http://schemas.datacontract.org/2004/07/TutoriasWcf.App_Data")]
    public partial class Turno : object
    {
        
        private string asuntoField;
        
        private int estadoTurnoField;
        
        private System.DateTime fechaTurnoField;
        
        private System.TimeSpan horaFinField;
        
        private System.TimeSpan horaInicioField;
        
        private int idTurnoField;
        
        private string matriculaEstudianteField;
        
        private string nombreEstudianteField;
        
        private string nombreTutorField;
        
        private System.Nullable<int> puntajeField;
        
        private System.Nullable<int> tiempoTutoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string asunto
        {
            get
            {
                return this.asuntoField;
            }
            set
            {
                this.asuntoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int estadoTurno
        {
            get
            {
                return this.estadoTurnoField;
            }
            set
            {
                this.estadoTurnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaTurno
        {
            get
            {
                return this.fechaTurnoField;
            }
            set
            {
                this.fechaTurnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan horaFin
        {
            get
            {
                return this.horaFinField;
            }
            set
            {
                this.horaFinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan horaInicio
        {
            get
            {
                return this.horaInicioField;
            }
            set
            {
                this.horaInicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTurno
        {
            get
            {
                return this.idTurnoField;
            }
            set
            {
                this.idTurnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matriculaEstudiante
        {
            get
            {
                return this.matriculaEstudianteField;
            }
            set
            {
                this.matriculaEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreEstudiante
        {
            get
            {
                return this.nombreEstudianteField;
            }
            set
            {
                this.nombreEstudianteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreTutor
        {
            get
            {
                return this.nombreTutorField;
            }
            set
            {
                this.nombreTutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> puntaje
        {
            get
            {
                return this.puntajeField;
            }
            set
            {
                this.puntajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> tiempoTutoria
        {
            get
            {
                return this.tiempoTutoriaField;
            }
            set
            {
                this.tiempoTutoriaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Tutor", Namespace="http://schemas.datacontract.org/2004/07/TutoriasWcf.App_Data")]
    public partial class Tutor : object
    {
        
        private ServiceReferenceTutorias.Horario[] HorariosField;
        
        private string apellidosField;
        
        private string correoField;
        
        private int idTutorField;
        
        private string nombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceTutorias.Horario[] Horarios
        {
            get
            {
                return this.HorariosField;
            }
            set
            {
                this.HorariosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidos
        {
            get
            {
                return this.apellidosField;
            }
            set
            {
                this.apellidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                this.correoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTutor
        {
            get
            {
                return this.idTutorField;
            }
            set
            {
                this.idTutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Horario", Namespace="http://schemas.datacontract.org/2004/07/TutoriasWcf.App_Data")]
    public partial class Horario : object
    {
        
        private ServiceReferenceTutorias.Tutor TutorField;
        
        private System.DateTime fechaTutoriaField;
        
        private System.TimeSpan horaFinField;
        
        private System.TimeSpan horaInicioField;
        
        private int idHorarioField;
        
        private int idTutorField;
        
        private string periodoEscolarField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceTutorias.Tutor Tutor
        {
            get
            {
                return this.TutorField;
            }
            set
            {
                this.TutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime fechaTutoria
        {
            get
            {
                return this.fechaTutoriaField;
            }
            set
            {
                this.fechaTutoriaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan horaFin
        {
            get
            {
                return this.horaFinField;
            }
            set
            {
                this.horaFinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan horaInicio
        {
            get
            {
                return this.horaInicioField;
            }
            set
            {
                this.horaInicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idHorario
        {
            get
            {
                return this.idHorarioField;
            }
            set
            {
                this.idHorarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTutor
        {
            get
            {
                return this.idTutorField;
            }
            set
            {
                this.idTutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string periodoEscolar
        {
            get
            {
                return this.periodoEscolarField;
            }
            set
            {
                this.periodoEscolarField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceTutorias.ITutoriasService")]
    public interface ITutoriasService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoriasService/RegistrarEstudiante", ReplyAction="http://tempuri.org/ITutoriasService/RegistrarEstudianteResponse")]
        System.Threading.Tasks.Task<bool> RegistrarEstudianteAsync(ServiceReferenceTutorias.Estudiante estudiante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoriasService/IniciarSesion", ReplyAction="http://tempuri.org/ITutoriasService/IniciarSesionResponse")]
        System.Threading.Tasks.Task<bool> IniciarSesionAsync(string matricula, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoriasService/RegistrarTurno", ReplyAction="http://tempuri.org/ITutoriasService/RegistrarTurnoResponse")]
        System.Threading.Tasks.Task<bool> RegistrarTurnoAsync(ServiceReferenceTutorias.Turno turno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoriasService/CambiarEstadoTurno", ReplyAction="http://tempuri.org/ITutoriasService/CambiarEstadoTurnoResponse")]
        System.Threading.Tasks.Task<bool> CambiarEstadoTurnoAsync(string asunto, int estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoriasService/ConsultarEstudiante", ReplyAction="http://tempuri.org/ITutoriasService/ConsultarEstudianteResponse")]
        System.Threading.Tasks.Task<ServiceReferenceTutorias.Estudiante> ConsultarEstudianteAsync(string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoriasService/ConsultarTurno", ReplyAction="http://tempuri.org/ITutoriasService/ConsultarTurnoResponse")]
        System.Threading.Tasks.Task<ServiceReferenceTutorias.Turno> ConsultarTurnoAsync(string matricula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoriasService/ConsultarListaTutores", ReplyAction="http://tempuri.org/ITutoriasService/ConsultarListaTutoresResponse")]
        System.Threading.Tasks.Task<ServiceReferenceTutorias.Tutor[]> ConsultarListaTutoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoriasService/ConsultarHorario", ReplyAction="http://tempuri.org/ITutoriasService/ConsultarHorarioResponse")]
        System.Threading.Tasks.Task<ServiceReferenceTutorias.Horario> ConsultarHorarioAsync(int idTutor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoriasService/ConsultarTutor", ReplyAction="http://tempuri.org/ITutoriasService/ConsultarTutorResponse")]
        System.Threading.Tasks.Task<ServiceReferenceTutorias.Tutor> ConsultarTutorAsync(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITutoriasService/RegristrarPuntaje", ReplyAction="http://tempuri.org/ITutoriasService/RegristrarPuntajeResponse")]
        System.Threading.Tasks.Task<bool> RegristrarPuntajeAsync(string asunto, int puntaje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface ITutoriasServiceChannel : ServiceReferenceTutorias.ITutoriasService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class TutoriasServiceClient : System.ServiceModel.ClientBase<ServiceReferenceTutorias.ITutoriasService>, ServiceReferenceTutorias.ITutoriasService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TutoriasServiceClient() : 
                base(TutoriasServiceClient.GetDefaultBinding(), TutoriasServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ITutoriasService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TutoriasServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TutoriasServiceClient.GetBindingForEndpoint(endpointConfiguration), TutoriasServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TutoriasServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TutoriasServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TutoriasServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TutoriasServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TutoriasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarEstudianteAsync(ServiceReferenceTutorias.Estudiante estudiante)
        {
            return base.Channel.RegistrarEstudianteAsync(estudiante);
        }
        
        public System.Threading.Tasks.Task<bool> IniciarSesionAsync(string matricula, string contraseña)
        {
            return base.Channel.IniciarSesionAsync(matricula, contraseña);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarTurnoAsync(ServiceReferenceTutorias.Turno turno)
        {
            return base.Channel.RegistrarTurnoAsync(turno);
        }
        
        public System.Threading.Tasks.Task<bool> CambiarEstadoTurnoAsync(string asunto, int estado)
        {
            return base.Channel.CambiarEstadoTurnoAsync(asunto, estado);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceTutorias.Estudiante> ConsultarEstudianteAsync(string matricula)
        {
            return base.Channel.ConsultarEstudianteAsync(matricula);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceTutorias.Turno> ConsultarTurnoAsync(string matricula)
        {
            return base.Channel.ConsultarTurnoAsync(matricula);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceTutorias.Tutor[]> ConsultarListaTutoresAsync()
        {
            return base.Channel.ConsultarListaTutoresAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceTutorias.Horario> ConsultarHorarioAsync(int idTutor)
        {
            return base.Channel.ConsultarHorarioAsync(idTutor);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceTutorias.Tutor> ConsultarTutorAsync(string correo)
        {
            return base.Channel.ConsultarTutorAsync(correo);
        }
        
        public System.Threading.Tasks.Task<bool> RegristrarPuntajeAsync(string asunto, int puntaje)
        {
            return base.Channel.RegristrarPuntajeAsync(asunto, puntaje);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITutoriasService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ITutoriasService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:57431/TutoriasService.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TutoriasServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ITutoriasService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TutoriasServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ITutoriasService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ITutoriasService,
        }
    }
}
