//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutoriasWcf.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string matricula { get; set; }
        public string contrasena { get; set; }
        public string correo { get; set; }
        public string nombreTutor { get; set; }
        public string carrera { get; set; }
        public int idEstudiante { get; set; }
    }
}
