//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutoriasWcf.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacion
    {
        public int idNotificacion { get; set; }
        public string asunto { get; set; }
        public string descripcion { get; set; }
        public int estadoLectura { get; set; }
        public System.DateTime fechaEnvio { get; set; }
        public string remitente { get; set; }
        public string destinatario { get; set; }
    }
}
